@extends('backend.layouts.app')

@section('content')
<div class="row"><div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex flex-wrap align-items-start justify-content-between"><div><h1 class="h3 mb-2">{{ translate('Addon Requests') }}</h1><p class="text-muted mb-0">{{ translate('CorePilotOS owns pricing, approval, setup decisions, and activation.') }}</p></div><a href="{{ route('subscription.index') }}" class="btn btn-soft-primary">{{ translate('View My Subscription') }}</a></div>
@if($usingFallbackCatalog)<div class="alert alert-warning mt-3 mb-0">{{ translate('Demo fallback catalog. Sync CorePilotOS to load current commercial availability.') }}</div>@endif
@if(!$requestConfigured)<div class="alert alert-info mt-3 mb-0">{{ translate('Requests are not configured for delivery yet. Contact support to request activation.') }}</div>@endif
@if(session('success'))<div class="alert alert-success mt-3 mb-0">{{ session('success') }}</div>@endif
@if($errors->has('addon_request'))<div class="alert alert-danger mt-3 mb-0">{{ $errors->first('addon_request') }}</div>@endif
</div></div></div></div>
<div class="row mt-3">@foreach($addonCatalog as $addon)@php($requestable = !empty($addon['is_available_as_addon']) && in_array($addon['status'] ?? '', ['available', 'requires_upgrade'], true))<div class="col-lg-6 col-xl-4 mb-3"><div class="card shadow-sm h-100"><div class="card-body d-flex flex-column"><div class="d-flex justify-content-between align-items-start mb-3"><h5 class="mb-0 h6">{{ translate($addon['name']) }}</h5><span class="badge badge-{{ in_array($addon['status'] ?? 'available',['included','active']) ? 'success' : (($addon['status'] ?? '') === 'requires_upgrade' ? 'warning' : 'info') }}">{{ translate(ucfirst(str_replace('_',' ', $addon['status'] ?? 'available'))) }}</span></div><p class="text-muted fs-13 flex-grow-1">{{ translate($addon['description'] ?? '') }}</p><div class="mb-3"><strong>{{ ($addon['monthly_price'] ?? null) !== null ? '$'.$addon['monthly_price'].' / month' : translate('Custom pricing') }}</strong>@if(!empty($addon['unit_label'])) <span class="text-muted">per {{ $addon['unit_label'] }}</span>@endif</div>
@if(!empty($addon['recommended_upgrade_plan']))<div class="alert alert-warning py-2 fs-12"><div>{{ translate('Recommended upgrade') }}: {{ ucfirst($addon['recommended_upgrade_plan']) }}</div>@if($requestable)<div class="mt-1">{{ translate('Upgrading may save you money') }}. {{ translate('This is a recommendation. You can still request this add-on.') }}</div>@endif<a href="{{ route('subscription.index') }}" class="btn btn-sm btn-soft-warning mt-2">{{ translate('Upgrade Plan') }}</a></div>@endif
@if($requestable)<form method="POST" action="{{ route('addons.request') }}">@csrf<input type="hidden" name="addon_code" value="{{ $addon['code'] }}">@if(!empty($addon['setup_available']))<label class="d-flex align-items-center fs-12 mb-2"><input type="checkbox" name="setup_requested" value="1" class="mr-2"> {{ translate('Request setup and onboarding assistance') }}</label><p class="text-muted fs-11">{{ translate('Setup fee to be confirmed by admin.') }}</p>@endif<textarea name="note" rows="2" class="form-control form-control-sm mb-2" placeholder="{{ translate('Optional note') }}"></textarea><button class="btn btn-soft-primary btn-block" @disabled(!$requestConfigured)>{{ translate('Request activation') }}</button></form>@endif
</div></div></div>@endforeach</div>
@endsection
