@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><h5 class="mb-0 h6">{{ translate('Purchase Receipts') }}</h5></div>
<div class="card"><div class="card-body">
    <form method="GET" class="row gutters-10 mb-3"><div class="col-md-3"><select class="form-control" name="supplier_id"><option value="">{{ translate('All suppliers') }}</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string) request('supplier_id') === (string) $supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div><div class="col-md-3"><input class="form-control" type="date" name="from" value="{{ request('from') }}"></div><div class="col-md-3"><input class="form-control" type="date" name="to" value="{{ request('to') }}"></div><div class="col-md-3"><button class="btn btn-soft-primary">{{ translate('Filter') }}</button></div></form>
    <div class="table-responsive"><table class="table aiz-table mb-0"><thead><tr><th>{{ translate('Receipt') }}</th><th>{{ translate('Purchase Order') }}</th><th>{{ translate('Supplier') }}</th><th>{{ translate('Received at') }}</th><th>{{ translate('Items') }}</th><th>{{ translate('Quantity') }}</th><th>{{ translate('Total Cost') }}</th><th></th></tr></thead><tbody>@forelse($receipts as $receipt)<tr><td>{{ $receipt->receipt_key }}</td><td>{{ $receipt->purchaseOrder?->purchase_number }}</td><td>{{ $receipt->purchaseOrder?->supplier?->name ?: '-' }}</td><td>{{ optional($receipt->received_at)->format('Y-m-d H:i') }}</td><td>{{ $receipt->items->count() }}</td><td>{{ coremarket_quantity($receipt->items->sum('quantity_received')) }}</td><td>{{ coremarket_money($receipt->items->sum('total_cost'), $receipt->purchaseOrder?->currency) }}</td><td class="text-right"><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.purchase-receipts.show', $receipt) }}">{{ translate('View') }}</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ translate('No purchase receipts found.') }}</td></tr>@endforelse</tbody></table></div>
    <div class="aiz-pagination">{{ $receipts->links() }}</div>
</div></div>
@endsection
