@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><div class="row"><div class="col"><h5 class="mb-0 h6">{{ $transfer->reference_no }}</h5></div><div class="col text-right"><a class="btn btn-soft-primary" href="{{ route('operations.inventory.stock-transfers.index') }}">{{ translate('Back to Transfers') }}</a></div></div></div>
@if($errors->has('stock_transfer'))<div class="alert alert-danger">{{ $errors->first('stock_transfer') }}</div>@endif
<div class="card"><div class="card-body">
    <div class="row"><div class="col-md-4"><strong>{{ translate('From') }}:</strong> {{ $transfer->fromBranch?->name }}</div><div class="col-md-4"><strong>{{ translate('To') }}:</strong> {{ $transfer->toBranch?->name }}</div><div class="col-md-4"><strong>{{ translate('Status') }}:</strong> {{ translate(ucwords(str_replace('_',' ',$transfer->status))) }}</div></div>
    <div class="table-responsive mt-3"><table class="table table-bordered"><thead><tr><th>{{ translate('Product') }}</th><th>{{ translate('SKU / Barcode') }}</th><th>{{ translate('Requested') }}</th><th>{{ translate('Shipped') }}</th><th>{{ translate('Received') }}</th></tr></thead><tbody>@foreach($transfer->items as $item)<tr><td>{{ $item->product_name_snapshot ?: '#'.$item->product_id }}</td><td>{{ $item->sku_snapshot ?: '-' }} / {{ $item->barcode_snapshot ?: '-' }}</td><td>{{ coremarket_quantity($item->quantity) }}</td><td>{{ coremarket_quantity($item->quantity_shipped ?? 0) }}</td><td>{{ coremarket_quantity($item->quantity_received ?? 0) }}</td></tr>@endforeach</tbody></table></div>
    <div class="d-flex flex-wrap gutters-5">
        @if($transfer->status === 'draft' && (auth()->user()?->user_type === 'admin' || auth()->user()?->can('inventory.stock_transfers.create')))<form method="POST" action="{{ route('operations.inventory.stock-transfers.submit', $transfer) }}">@csrf<button class="btn btn-primary">{{ translate('Submit') }}</button></form>@endif
        @if($transfer->status === 'pending_approval' && (auth()->user()?->user_type === 'admin' || auth()->user()?->can('inventory.stock_transfers.approve')))<form method="POST" action="{{ route('operations.inventory.stock-transfers.approve', $transfer) }}">@csrf<button class="btn btn-success">{{ translate('Approve') }}</button></form><form method="POST" action="{{ route('operations.inventory.stock-transfers.reject', $transfer) }}">@csrf<button class="btn btn-soft-danger">{{ translate('Reject') }}</button></form>@endif
        @if($transfer->status === 'approved' && (auth()->user()?->user_type === 'admin' || auth()->user()?->can('inventory.stock_transfers.ship')))<form method="POST" action="{{ route('operations.inventory.stock-transfers.ship', $transfer) }}">@csrf<button class="btn btn-warning">{{ translate('Ship') }}</button></form>@endif
        @if($transfer->status === 'shipped' && (auth()->user()?->user_type === 'admin' || auth()->user()?->can('inventory.stock_transfers.receive')))<form method="POST" action="{{ route('operations.inventory.stock-transfers.receive', $transfer) }}">@csrf<button class="btn btn-success">{{ translate('Receive') }}</button></form>@endif
        @if(in_array($transfer->status,['draft','pending_approval','approved']) && (auth()->user()?->user_type === 'admin' || auth()->user()?->can('inventory.stock_transfers.cancel')))<form method="POST" action="{{ route('operations.inventory.stock-transfers.cancel', $transfer) }}">@csrf<button class="btn btn-soft-dark">{{ translate('Cancel') }}</button></form>@endif
    </div>
</div></div>
@endsection
