@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><div class="row"><div class="col"><h5 class="mb-0 h6">{{ $purchaseOrder->purchase_number }} <span class="badge badge-info">{{ translate(ucfirst(str_replace('_', ' ', $purchaseOrder->status))) }}</span></h5></div><div class="col text-right"><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.purchase-receipts') }}">{{ translate('Purchase Receipts') }}</a></div></div></div>
<div class="card"><div class="card-body"><div class="row"><div class="col-md-4"><strong>{{ translate('Supplier') }}:</strong> {{ $purchaseOrder->supplier?->name ?: '-' }}</div><div class="col-md-4"><strong>{{ translate('Ordered') }}:</strong> {{ optional($purchaseOrder->ordered_at)->format('Y-m-d') ?: '-' }}</div><div class="col-md-4"><strong>{{ translate('Progress') }}:</strong> {{ coremarket_quantity($progress['received']) }} / {{ coremarket_quantity($progress['ordered']) }} ({{ translate('Remaining') }} {{ coremarket_quantity($progress['remaining']) }})</div></div>
<div class="table-responsive mt-3"><table class="table table-bordered"><thead><tr><th>{{ translate('Product') }}</th><th>{{ translate('Variant / SKU / Barcode') }}</th><th>{{ translate('Ordered') }}</th><th>{{ translate('Received') }}</th><th>{{ translate('Cost Price') }}</th><th>{{ translate('Regular Price') }}</th><th>{{ translate('Sale Price') }}</th><th>{{ translate('Margin') }}</th><th>{{ translate('Tax') }}</th><th>{{ translate('Line Total') }}</th></tr></thead><tbody>@foreach($purchaseOrder->items as $item)@php($pricing = $item->metadata['pricing_snapshot'] ?? [])@php($tax = $item->metadata['tax_snapshot'] ?? [])<tr><td>{{ $item->product?->name ?: '#'.$item->product_id }}</td><td>{{ $item->productStock?->variant ?: $item->variant ?: '-' }}<br><small>{{ $item->productStock?->sku ?: '-' }} / {{ $item->productStock?->barcode ?: $item->product?->barcode ?: '-' }}</small></td><td>{{ coremarket_quantity($item->quantity_ordered) }}</td><td>{{ coremarket_quantity($item->quantity_received) }}</td><td>{{ coremarket_money($item->unit_cost, $purchaseOrder->currency) }}</td><td>{{ isset($pricing['regular_price']) ? coremarket_money($pricing['regular_price'], $purchaseOrder->currency) : '-' }}</td><td>{{ isset($pricing['sale_price']) ? coremarket_money($pricing['sale_price'], $purchaseOrder->currency) : '-' }}</td><td>{{ isset($pricing['margin_percent']) ? coremarket_number($pricing['margin_percent']).'%' : '-' }}</td><td>{{ coremarket_money($item->tax_amount, $purchaseOrder->currency) }}@if(isset($tax['rate']))<br><small>{{ coremarket_number($tax['rate']) }}%</small>@endif</td><td>{{ coremarket_money($item->metadata['line_total'] ?? $item->total_cost, $purchaseOrder->currency) }}</td></tr>@endforeach</tbody></table></div>
<div class="text-right">
    <div><strong>{{ translate('Subtotal') }}:</strong> {{ coremarket_money($purchaseOrder->subtotal_amount, $purchaseOrder->currency) }}</div>
    <div><strong>{{ translate('Tax') }}:</strong> {{ coremarket_money($purchaseOrder->tax_amount, $purchaseOrder->currency) }}</div>
    <div><strong>{{ translate('Discount') }}:</strong> {{ coremarket_money($purchaseOrder->discount_amount, $purchaseOrder->currency) }}</div>
    <div><strong>{{ translate('Total') }}:</strong> {{ coremarket_money($purchaseOrder->total_amount, $purchaseOrder->currency) }}</div>
</div></div></div>

@can('purchase_orders.receive')
@if(!in_array($purchaseOrder->status, ['received', 'cancelled']))
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Receive remaining items') }}</h6></div><div class="card-body"><form method="POST" action="{{ route('operations.purchase-orders.receive', $purchaseOrder) }}">@csrf
    <div class="form-group"><label>{{ translate('Receipt key') }}</label><input class="form-control" name="receipt_key" value="web-{{ $purchaseOrder->id }}-{{ now()->format('YmdHis') }}" required><small class="text-muted">{{ translate('Keep this key when retrying the same receipt.') }}</small></div>
    @foreach($purchaseOrder->items as $item)
    @if($item->quantity_ordered > $item->quantity_received)
    <div class="row gutters-10 align-items-end mb-2"><input type="hidden" name="items[{{ $loop->index }}][purchase_order_item_id]" value="{{ $item->id }}"><div class="col-md-4"><label>{{ $item->product?->name ?: '#'.$item->product_id }}</label><div class="form-control-plaintext small">{{ translate('Ordered') }} {{ coremarket_quantity($item->quantity_ordered) }} · {{ translate('Received') }} {{ coremarket_quantity($item->quantity_received) }} · {{ translate('Remaining') }} {{ coremarket_quantity($item->quantity_ordered - $item->quantity_received) }}</div></div><div class="col-md-3"><label>{{ translate('Receive now') }}</label><input class="form-control" name="items[{{ $loop->index }}][quantity_received]" type="number" step="0.000001" min="0" max="{{ $item->quantity_ordered - $item->quantity_received }}" value="0"></div><div class="col-md-3"><label>{{ translate('Unit Cost') }}</label><input class="form-control" name="items[{{ $loop->index }}][unit_cost]" type="number" step="0.000001" min="0" value="{{ $item->unit_cost }}"></div></div>
    @endif
    @endforeach
    <div class="form-group"><label>{{ translate('Notes') }}</label><textarea class="form-control" name="notes"></textarea></div><button class="btn btn-success">{{ translate('Receive') }}</button>
</form></div></div>
@endif
@endcan

<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Receipts history') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Receipt') }}</th><th>{{ translate('Received at') }}</th><th>{{ translate('Items') }}</th><th>{{ translate('Received quantity') }}</th><th></th></tr></thead><tbody>@forelse($purchaseOrder->receipts as $receipt)<tr><td>{{ $receipt->receipt_key }}</td><td>{{ optional($receipt->received_at)->format('Y-m-d H:i') }}</td><td>{{ $receipt->items->count() }}</td><td>{{ $receipt->items->sum('quantity_received') }}</td><td><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.purchase-receipts.show', $receipt) }}">{{ translate('View') }}</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ translate('No receipts yet.') }}</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Inventory movement trace') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Date') }}</th><th>{{ translate('Product') }}</th><th>{{ translate('Quantity') }}</th><th>{{ translate('Unit Cost') }}</th><th>{{ translate('Total Cost') }}</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->created_at }}</td><td>{{ $movement->product?->name ?: '#'.$movement->product_id }}</td><td>{{ coremarket_quantity($movement->quantity) }}</td><td>{{ coremarket_money($movement->unit_cost, $purchaseOrder->currency) }}</td><td>{{ coremarket_money($movement->total_cost, $purchaseOrder->currency) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ translate('No linked movements.') }}</td></tr>@endforelse</tbody></table></div></div>
@endsection
