@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><div class="row"><div class="col"><h5 class="mb-0 h6">{{ $purchaseOrder->purchase_number }} <span class="badge badge-info">{{ translate(ucfirst(str_replace('_', ' ', $purchaseOrder->status))) }}</span></h5></div><div class="col text-right"><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.purchase-receipts') }}">{{ translate('Purchase Receipts') }}</a></div></div></div>
<div class="card"><div class="card-body"><div class="row"><div class="col-md-4"><strong>{{ translate('Supplier') }}:</strong> {{ $purchaseOrder->supplier?->name ?: '-' }}</div><div class="col-md-4"><strong>{{ translate('Ordered') }}:</strong> {{ optional($purchaseOrder->ordered_at)->format('Y-m-d') ?: '-' }}</div><div class="col-md-4"><strong>{{ translate('Progress') }}:</strong> {{ $progress['received'] }} / {{ $progress['ordered'] }} ({{ translate('Remaining') }} {{ $progress['remaining'] }})</div></div>
<div class="table-responsive mt-3"><table class="table table-bordered"><thead><tr><th>{{ translate('Product') }}</th><th>{{ translate('Variant / SKU / Barcode') }}</th><th>{{ translate('Ordered') }}</th><th>{{ translate('Received') }}</th><th>{{ translate('Remaining') }}</th><th>{{ translate('Unit Cost') }}</th><th>{{ translate('Total Cost') }}</th></tr></thead><tbody>@foreach($purchaseOrder->items as $item)<tr><td>{{ $item->product?->name ?: '#'.$item->product_id }}</td><td>{{ $item->productStock?->variant ?: $item->variant ?: '-' }}<br><small>{{ $item->productStock?->sku ?: '-' }} / {{ $item->productStock?->barcode ?: $item->product?->barcode ?: '-' }}</small></td><td>{{ $item->quantity_ordered }}</td><td>{{ $item->quantity_received }}</td><td>{{ max(0, $item->quantity_ordered - $item->quantity_received) }}</td><td>{{ $item->unit_cost }}</td><td>{{ $item->total_cost }}</td></tr>@endforeach</tbody></table></div>
<p class="mb-0"><strong>{{ translate('Total') }}:</strong> {{ $purchaseOrder->total_amount }} {{ $purchaseOrder->currency }}</p></div></div>

@can('purchase_orders.receive')
@if(!in_array($purchaseOrder->status, ['received', 'cancelled']))
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Receive remaining items') }}</h6></div><div class="card-body"><form method="POST" action="{{ route('operations.purchase-orders.receive', $purchaseOrder) }}">@csrf
    <div class="form-group"><label>{{ translate('Receipt key') }}</label><input class="form-control" name="receipt_key" value="web-{{ $purchaseOrder->id }}-{{ now()->format('YmdHis') }}" required><small class="text-muted">{{ translate('Keep this key when retrying the same receipt.') }}</small></div>
    @foreach($purchaseOrder->items as $item)
    @if($item->quantity_ordered > $item->quantity_received)
    <div class="row gutters-10 align-items-end mb-2"><input type="hidden" name="items[{{ $loop->index }}][purchase_order_item_id]" value="{{ $item->id }}"><div class="col-md-4"><label>{{ $item->product?->name ?: '#'.$item->product_id }}</label><div class="form-control-plaintext small">{{ translate('Ordered') }} {{ $item->quantity_ordered }} · {{ translate('Received') }} {{ $item->quantity_received }} · {{ translate('Remaining') }} {{ $item->quantity_ordered - $item->quantity_received }}</div></div><div class="col-md-3"><label>{{ translate('Receive now') }}</label><input class="form-control" name="items[{{ $loop->index }}][quantity_received]" type="number" step="0.000001" min="0" max="{{ $item->quantity_ordered - $item->quantity_received }}" value="0"></div><div class="col-md-3"><label>{{ translate('Unit Cost') }}</label><input class="form-control" name="items[{{ $loop->index }}][unit_cost]" type="number" step="0.000001" min="0" value="{{ $item->unit_cost }}"></div></div>
    @endif
    @endforeach
    <div class="form-group"><label>{{ translate('Notes') }}</label><textarea class="form-control" name="notes"></textarea></div><button class="btn btn-success">{{ translate('Receive') }}</button>
</form></div></div>
@endif
@endcan

<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Receipts history') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Receipt') }}</th><th>{{ translate('Received at') }}</th><th>{{ translate('Items') }}</th><th>{{ translate('Received quantity') }}</th><th></th></tr></thead><tbody>@forelse($purchaseOrder->receipts as $receipt)<tr><td>{{ $receipt->receipt_key }}</td><td>{{ optional($receipt->received_at)->format('Y-m-d H:i') }}</td><td>{{ $receipt->items->count() }}</td><td>{{ $receipt->items->sum('quantity_received') }}</td><td><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.purchase-receipts.show', $receipt) }}">{{ translate('View') }}</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ translate('No receipts yet.') }}</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Inventory movement trace') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Date') }}</th><th>{{ translate('Product') }}</th><th>{{ translate('Quantity') }}</th><th>{{ translate('Unit Cost') }}</th><th>{{ translate('Total Cost') }}</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->created_at }}</td><td>{{ $movement->product?->name ?: '#'.$movement->product_id }}</td><td>{{ $movement->quantity }}</td><td>{{ $movement->unit_cost }}</td><td>{{ $movement->total_cost }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ translate('No linked movements.') }}</td></tr>@endforelse</tbody></table></div></div>
@endsection
