<?php

return [
    'plan' => [
        'code' => env('COREMARKET_PLAN_CODE', env('COREMARKET_APPLIED_PLAN_CODE', 'starter')),
    ],

    'runtime' => [
        'default_applied_plan' => 'starter',
        'applied_plan_code' => env('COREMARKET_APPLIED_PLAN_CODE', env('COREMARKET_PLAN_CODE', 'starter')),
        'default_store_mode' => 'single_store',
        'store_mode' => env('COREMARKET_STORE_MODE', env('COREMARKET_LICENSE_STORE_MODE', 'single_store')),

        'plan_aliases' => [
            'ecommerce_starter' => 'starter',
            'starter' => 'starter',
            'business' => 'business',
            'marketplace' => 'marketplace',
            'enterprise' => 'enterprise',
        ],

        'store_mode_aliases' => [
            'single_store' => 'single_store',
            'single-store' => 'single_store',
            'marketplace' => 'marketplace',
            'owned_coremarket_store' => 'owned_coremarket_store',
            'owned-coremarket-store' => 'owned_coremarket_store',
        ],

        'feature_aliases' => [
            'vendor_mode_enabled' => 'multi_vendor',
            'seller_registration_enabled' => 'sellers',
            'seller_panel_enabled' => 'sellers',
            'pos_enabled' => 'pos',
            'advanced_reports_enabled' => 'reports_advanced',
            'basic_loyalty_enabled' => 'loyalty_points',
        ],

        'feature_definitions' => [
            'multi_vendor' => ['default' => false],
            'sellers' => ['default' => false],
            'pos' => ['default' => false],
            'blog' => ['default' => false],
            'marketing_basic' => ['default' => true],
            'marketing_advanced' => ['default' => false],
            'support_basic' => ['default' => true],
            'support_advanced' => ['default' => false],
            'staff_management' => ['default' => true],
            'reports_basic' => ['default' => true],
            'reports_advanced' => ['default' => false],
            'uploads_manager' => ['default' => true],
            'loyalty_points' => ['default' => true],
            'website_appearance' => ['default' => true],
            'website_pages_limited' => ['default' => true],
            'translations_limited' => ['default' => true],
            'currencies_limited' => ['default' => true],
            'addon_requests' => ['default' => true],
            'subscription_page' => ['default' => true],
        ],

        'limit_definitions' => [
            'products_limit' => ['default' => 50],
            'monthly_orders_limit' => ['default' => 300],
            'staff_limit' => ['default' => 3],
            'sellers_limit' => ['default' => 0],
            'storage_mb_limit' => ['default' => 1024],
        ],

        'plans' => [
            'starter' => [
                'default_store_mode' => 'single_store',
                'features' => [
                    'multi_vendor' => false,
                    'sellers' => false,
                    'pos' => false,
                    'blog' => true,
                    'marketing_basic' => true,
                    'marketing_advanced' => false,
                    'support_basic' => true,
                    'support_advanced' => false,
                    'staff_management' => true,
                    'reports_basic' => true,
                    'reports_advanced' => false,
                    'uploads_manager' => true,
                    'loyalty_points' => true,
                    'website_appearance' => true,
                    'website_pages_limited' => true,
                    'translations_limited' => true,
                    'currencies_limited' => true,
                    'addon_requests' => true,
                    'subscription_page' => true,
                ],
                'limits' => [
                    'products_limit' => 50,
                    'monthly_orders_limit' => 300,
                    'staff_limit' => 3,
                    'sellers_limit' => 0,
                    'storage_mb_limit' => 1024,
                ],
            ],
            'business' => [
                'default_store_mode' => 'single_store',
                'features' => [
                    'multi_vendor' => false,
                    'sellers' => false,
                    'pos' => true,
                    'blog' => true,
                    'marketing_basic' => true,
                    'marketing_advanced' => true,
                    'support_basic' => true,
                    'support_advanced' => true,
                    'staff_management' => true,
                    'reports_basic' => true,
                    'reports_advanced' => true,
                    'uploads_manager' => true,
                    'loyalty_points' => true,
                    'website_appearance' => true,
                    'website_pages_limited' => true,
                    'translations_limited' => true,
                    'currencies_limited' => true,
                    'addon_requests' => true,
                    'subscription_page' => true,
                ],
                'limits' => [
                    'products_limit' => 500,
                    'monthly_orders_limit' => 5000,
                    'staff_limit' => 15,
                    'sellers_limit' => 0,
                    'storage_mb_limit' => 5120,
                ],
            ],
            'marketplace' => [
                'default_store_mode' => 'marketplace',
                'features' => [
                    'multi_vendor' => true,
                    'sellers' => true,
                    'pos' => true,
                    'blog' => true,
                    'marketing_basic' => true,
                    'marketing_advanced' => true,
                    'support_basic' => true,
                    'support_advanced' => true,
                    'staff_management' => true,
                    'reports_basic' => true,
                    'reports_advanced' => true,
                    'uploads_manager' => true,
                    'loyalty_points' => true,
                    'website_appearance' => true,
                    'website_pages_limited' => true,
                    'translations_limited' => true,
                    'currencies_limited' => true,
                    'addon_requests' => true,
                    'subscription_page' => true,
                ],
                'limits' => [
                    'products_limit' => 5000,
                    'monthly_orders_limit' => 25000,
                    'staff_limit' => 50,
                    'sellers_limit' => 1000,
                    'storage_mb_limit' => 20480,
                ],
            ],
            'enterprise' => [
                'default_store_mode' => 'owned_coremarket_store',
                'features' => [
                    'multi_vendor' => true,
                    'sellers' => true,
                    'pos' => true,
                    'blog' => true,
                    'marketing_basic' => true,
                    'marketing_advanced' => true,
                    'support_basic' => true,
                    'support_advanced' => true,
                    'staff_management' => true,
                    'reports_basic' => true,
                    'reports_advanced' => true,
                    'uploads_manager' => true,
                    'loyalty_points' => true,
                    'website_appearance' => true,
                    'website_pages_limited' => true,
                    'translations_limited' => true,
                    'currencies_limited' => true,
                    'addon_requests' => true,
                    'subscription_page' => true,
                ],
                'limits' => [
                    'products_limit' => null,
                    'monthly_orders_limit' => null,
                    'staff_limit' => null,
                    'sellers_limit' => null,
                    'storage_mb_limit' => null,
                ],
            ],
        ],

        'store_modes' => [
            'single_store' => [
                'feature_overrides' => [
                    'multi_vendor' => false,
                    'sellers' => false,
                ],
                'limit_overrides' => [],
            ],
            'marketplace' => [
                'feature_overrides' => [
                    'multi_vendor' => true,
                    'sellers' => true,
                ],
                'limit_overrides' => [],
            ],
            'owned_coremarket_store' => [
                'feature_overrides' => [
                    'multi_vendor' => false,
                    'sellers' => false,
                ],
                'limit_overrides' => [],
            ],
        ],
    ],

    'runtime_sync' => [
        'token' => env('COREPILOT_RUNTIME_SYNC_TOKEN'),
        'header' => 'X-CorePilot-Sync-Token',
    ],

    'runtime_snapshot' => [
        'setting_keys' => [
            'status' => 'coremarket_runtime_status',
            'applied_plan' => 'coremarket_runtime_applied_plan',
            'store_mode' => 'coremarket_runtime_store_mode',
            'features' => 'coremarket_runtime_features',
            'limits' => 'coremarket_runtime_limits',
            'store_metadata' => 'coremarket_runtime_store_metadata',
            'support_metadata' => 'coremarket_runtime_support_metadata',
        ],
        'allowed_store_metadata' => [
            'instance_id',
            'store_name',
            'store_url',
            'admin_url',
            'pos_url',
            'api_base_url',
        ],
        'allowed_support_metadata' => [
            'company_name',
            'support_email',
        ],
    ],

    'license' => [
        'license_enabled' => env('COREMARKET_LICENSE_ENABLED', false),
        'instance_id' => env('COREMARKET_INSTANCE_ID'),
        'license_key' => env('COREMARKET_LICENSE_KEY'),
        'domain' => env(
            'COREMARKET_LICENSE_DOMAIN',
            parse_url(env('APP_URL', ''), PHP_URL_HOST) ?: env('APP_URL')
        ),
        'applied_plan_code' => env('COREMARKET_APPLIED_PLAN_CODE', env('COREMARKET_PLAN_CODE', 'starter')),
        'plan_code' => env('COREMARKET_PLAN_CODE', env('COREMARKET_APPLIED_PLAN_CODE', 'starter')),
        'store_mode' => env('COREMARKET_LICENSE_STORE_MODE', env('COREMARKET_STORE_MODE', 'single_store')),
        'status' => env('COREMARKET_LICENSE_STATUS', 'active'),
        'starts_at' => env('COREMARKET_LICENSE_STARTS_AT'),
        'expires_at' => env('COREMARKET_LICENSE_EXPIRES_AT'),
        'grace_until' => env('COREMARKET_LICENSE_GRACE_UNTIL'),
        'suspension_reason' => env('COREMARKET_LICENSE_SUSPENSION_REASON'),
        'feature_overrides' => [],
        'limit_overrides' => [],
    ],

    'features' => [
        'pos_enabled' => false,
        'payment_gateway_enabled' => false,
        'vendor_mode_enabled' => false,
        'seller_registration_enabled' => false,
        'seller_panel_enabled' => false,
        'mobile_app_links_enabled' => false,
        'advanced_reports_enabled' => false,
        'delivery_boy_enabled' => false,
        'carrier_shipping_enabled' => false,
        'wallet_enabled' => false,
        'seller_packages_enabled' => false,
        'basic_loyalty_enabled' => true,
        'whatsapp_orders_enabled' => true,
    ],

    'limits' => [
        'products_limit' => 50,
        'monthly_orders_limit' => 300,
        'staff_limit' => 3,
        'sellers_limit' => 0,
        'storage_mb_limit' => 1024,
    ],

    'contact' => [
        'resolve_from_settings' => true,
        'whatsapp_number' => null,
        'contact_phone' => null,
        'helpline_number' => null,
    ],

    'instance_setup' => [
        'default_plan' => 'starter',
        'default_store_mode' => 'single_store',
        'default_currency_code' => 'USD',
        'default_language_code' => 'en',

        'business_settings_map' => [
            'website_name' => 'store_name',
            'site_name' => 'store_name',
            'site_motto' => 'site_motto',
            'meta_title' => 'meta_title',
            'meta_description' => 'meta_description',
            'contact_address' => 'contact_address',
            'contact_phone' => 'contact_phone',
            'contact_email' => 'support_email',
            'helpline_number' => 'whatsapp',
            'frontend_copyright_text' => 'footer_text',
            'vendor_system_activation' => 'vendor_system_activation',
            'wallet_system' => 'wallet_system',
            'cash_payment' => 1,
            'show_website_popup' => 0,
            'timezone' => 'timezone',
            'system_default_currency' => 'system_default_currency',
        ],

        'safe_setting_defaults' => [
            'topbar_banner_link' => '',
            'watermark_text' => '',
            'seller_app_link' => '',
            'delivery_boy_app_link' => '',
            'play_store_link' => '',
            'app_store_link' => '',
        ],

        'runtime_feature_to_legacy_setting_map' => [
            'multi_vendor' => 'vendor_system_activation',
            'wallet_enabled' => 'wallet_system',
        ],

        'media_notes' => [
            'Logo/media must be uploaded manually and assigned through business_settings upload IDs.',
            'Do not commit client logos, favicons, or uploaded media to Git.',
        ],
    ],

    'storefront_cleanup' => [
        'setting_defaults' => [
            'website_name' => 'CoreMarket',
            'site_name' => 'CoreMarket',
            'site_motto' => 'Modern managed ecommerce storefront',
            'meta_title' => 'CoreMarket',
            'meta_description' => 'Modern managed ecommerce storefront',
            'contact_phone' => '',
            'contact_email' => '',
            'topbar_banner_link' => '',
            'header_menu_links' => '["/","/products","/categories","/flash-deals"]',
            'widget_one_links' => '["/privacy-policy","/terms","/support-policy","/return-policy"]',
            'watermark_text' => '',
            'seller_app_link' => '',
            'delivery_boy_app_link' => '',
            'play_store_link' => '',
            'app_store_link' => '',
            'show_website_popup' => '0',
        ],

        'localized_setting_defaults' => [
            'footer_title' => 'CoreMarket',
            'frontend_copyright_text' => '© CoreMarket. All rights reserved.',
            'website_popup_content' => '',
        ],

        'notes' => [
            'This cleanup targets business_settings only.',
            'It does not modify products, orders, users, shops, uploads, or logo upload IDs.',
            'Popup marketing should be disabled in the managed baseline unless a client explicitly configures it later.',
            'Cookie agreement content remains configurable per instance.',
        ],
    ],

    'clean_baseline' => [
        'setting_defaults' => [
            'website_name' => 'CoreMarket Store',
            'site_name' => 'CoreMarket Store',
            'site_motto' => 'Managed commerce platform',
            'meta_title' => 'CoreMarket Store',
            'meta_description' => 'Managed ecommerce store powered by CoreMarket',
            'contact_email' => 'support@example.com',
            'contact_phone' => '',
            'contact_address' => '',
            'frontend_copyright_text' => '© CoreMarket Store. All rights reserved.',
            'footer_title' => 'CoreMarket Store',
            'watermark_text' => '',
            'topbar_banner_link' => '',
            'header_menu_links' => '["/","/products","/categories"]',
            'widget_one_links' => '["/privacy-policy","/terms","/support-policy","/return-policy"]',
            'home_slider_links' => '[]',
            'home_banner1_links' => '[]',
            'home_banner2_links' => '[]',
            'home_banner3_links' => '[]',
            'home_banner4_links' => '[]',
            'home_banner5_links' => '[]',
            'home_banner6_links' => '[]',
            'show_website_popup' => '0',
            'website_popup_content' => '',
            'vendor_system_activation' => '0',
            'wallet_system' => '0',
            'cash_payment' => '1',
            'payumoney_payment' => '0',
            'show_social_links' => '0',
            'seller_app_link' => '',
            'delivery_boy_app_link' => '',
            'play_store_link' => '',
            'app_store_link' => '',
        ],

        'legacy_terms' => [
            'Syrian Souq',
            'syriansouq',
            'syrian_souq',
            'Coin Market',
            'coin-market',
            'shaheen',
            'الشاهين',
            'demo.coin-market.store',
            'http://localhost/syrian-souq',
            'https://syriansouq.com',
        ],

        'notes' => [
            'This workflow updates business_settings only and never deletes tables.',
            'It does not delete products, orders, uploads, shops, or other client/demo data.',
            'Logo and media upload IDs are left unchanged and should be replaced later through instance-specific setup.',
            'DEFAULT_LANGUAGE remains an environment/runtime setting and should be kept at English for the clean baseline runtime.',
            'Use coremarket:setup-instance to apply real client store name, domain, support contacts, and runtime plan values later.',
            'If you need catalog or upload cleanup later, implement it as a separate reset command rather than extending this safe baseline workflow.',
        ],
    ],

    'access' => [
        'store_admin_role' => 'store_admin',

        'store_admin_permissions' => [
            'admin_dashboard',

            'add_new_product',
            'show_in_house_products',
            'product_edit',
            'product_delete',
            'product_duplicate',

            'view_product_categories',
            'add_product_category',
            'edit_product_category',
            'delete_product_category',

            'view_all_brands',
            'add_brand',
            'edit_brand',
            'delete_brand',

            'view_inhouse_orders',
            'view_order_details',
            'update_order_delivery_status',
            'update_order_payment_status',

            'view_all_coupons',
            'add_coupon',
            'edit_coupon',
            'delete_coupon',

            'header_setup',
            'footer_setup',
            'view_all_website_pages',
            'add_website_page',
            'edit_website_page',
            'delete_website_page',
        ],

        'store_admin_allowed_business_setting_types' => [
            'header_logo',
            'show_language_switcher',
            'show_currency_switcher',
            'header_stikcy',
            'topbar_banner',
            'topbar_banner_medium',
            'topbar_banner_small',
            'topbar_banner_link',
            'helpline_number',
            'header_nav_menu_text',
            'header_menu_labels',
            'header_menu_links',

            'footer_title',
            'footer_description',
            'footer_logo',
            'about_us_description',
            'contact_address',
            'contact_phone',
            'contact_email',
            'widget_one',
            'widget_one_labels',
            'widget_one_links',
            'widget_two',
            'widget_two_labels',
            'widget_two_links',
            'widget_three',
            'widget_three_labels',
            'widget_three_links',
            'frontend_copyright_text',
            'show_social_links',
            'facebook_link',
            'twitter_link',
            'instagram_link',
            'youtube_link',
            'linkedin_link',
        ],

        'store_admin_blocked_route_names' => [
            'update',
            'update.*',
            'activation.index',
            'payment.activation',
            'payment_method.index',
            'payment_method.update',
            'env_key_update.update',
            'google_analytics.update',
            'google_recaptcha.update',
            'google-map.update',
            'google-firebase.update',
            'business_settings.update.activation',
            'business_settings.vendor_commission.update',
            'business_settings.vendor_commission',
            'seller_verification_form.update',
            'shipping_configuration.update',
            'roles.*',
            'staffs.*',
            'addons.create',
            'addons.store',
            'addons.show',
            'addons.edit',
            'addons.update',
            'addons.destroy',
            'addons.activation',
            'sellers.*',
            'seller.requests.*',
            'withdraw_requests.*',
            'notification.settings',
            'notification-type.*',
            'notification_type.*',
            'custom_notification*',
            'custom-notifications.*',
            'custom_notified_customers_list',
            'currency.*',
            'your_currency.update',
            'tax.*',
            'languages.*',
            'app-translations.*',
            'customer_packages.*',
            'seller_packages.*',
            'pickup_point.*',
            'countries.*',
            'states.*',
            'carriers.*',
            'zones.*',
            'cities.*',
            'delivery-boys.*',
            'delivery-boy.*',
            'delivery-boy-configuration',
            'delivery-boys-payment-histories',
            'delivery-boys-collection-histories',
            'paid-to-delivery-boy',
            'collection-from-delivery-boy',
            'orders.delivery-boy-assign',
            'earning_payout_report.index',
            'in_house_sale_report.index',
            'seller_sale_report.index',
            'stock_report.index',
            'wish_report.index',
            'user_search_report.index',
            'commission-log.index',
            'wallet-history.index',
            'cache.clear',
            'system_update',
            'import_demo_data',
            'uploaded-files.*',
            'bulk-uploaded-files-delete',
            'poin-of-sales.*',
            'pos.*',
            'admin.invoice.thermal_printer',
            'website.select-homepage',
            'website.authentication-layout-settings',
            'website.appearance',
        ],

        'store_admin_blocked_route_uris' => [
            'admin/admin-permissions',
            'admin/all-file',
        ],
    ],

    'qa_seed' => [
        'default_password' => env('COREMARKET_QA_PASSWORD', 'qa-coremarket-local'),

        'customer' => [
            'name' => 'QA CoreMarket Customer',
            'email' => 'qa.customer.coremarket@example.test',
            'phone' => '+10000000001',
        ],

        'store_admin' => [
            'name' => 'QA CoreMarket Store Admin',
            'email' => 'qa.storeadmin.coremarket@example.test',
            'phone' => '+10000000002',
        ],

        'category' => [
            'name' => 'QA CoreMarket Category',
            'slug' => 'qa-coremarket-category',
        ],

        'product' => [
            'name' => 'QA CoreMarket Sample Product',
            'slug' => 'qa-coremarket-sample-product',
            'unit_price' => 25,
            'current_stock' => 10,
            'unit' => 'pc',
            'description' => 'QA CoreMarket sample product for local end-to-end checkout testing.',
        ],

        'settings' => [
            'cash_payment' => '1',
            'vendor_system_activation' => '0',
            'wallet_system' => '0',
            'show_website_popup' => '0',
            'show_cookies_agreement' => '0',
        ],
    ],
];
