<?php

return [
    'plan' => [
        'code' => 'ecommerce_starter',
    ],

    'features' => [
        'pos_enabled' => false,
        'payment_gateway_enabled' => false,
        'vendor_mode_enabled' => false,
        'seller_registration_enabled' => false,
        'seller_panel_enabled' => false,
        'mobile_app_links_enabled' => false,
        'advanced_reports_enabled' => false,
        'delivery_boy_enabled' => false,
        'carrier_shipping_enabled' => false,
        'wallet_enabled' => false,
        'seller_packages_enabled' => false,
        'basic_loyalty_enabled' => true,
        'whatsapp_orders_enabled' => true,
    ],

    'limits' => [
        'products_limit' => 50,
        'monthly_orders_limit' => 300,
    ],

    'access' => [
        'store_admin_role' => 'store_admin',

        'store_admin_permissions' => [
            'admin_dashboard',

            'add_new_product',
            'show_in_house_products',
            'product_edit',
            'product_delete',
            'product_duplicate',

            'view_product_categories',
            'add_product_category',
            'edit_product_category',
            'delete_product_category',

            'view_all_brands',
            'add_brand',
            'edit_brand',
            'delete_brand',

            'view_inhouse_orders',
            'view_order_details',
            'update_order_delivery_status',
            'update_order_payment_status',

            'view_all_coupons',
            'add_coupon',
            'edit_coupon',
            'delete_coupon',

            'header_setup',
            'footer_setup',
            'view_all_website_pages',
            'add_website_page',
            'edit_website_page',
            'delete_website_page',
        ],

        'store_admin_allowed_business_setting_types' => [
            'header_logo',
            'show_language_switcher',
            'show_currency_switcher',
            'header_stikcy',
            'topbar_banner',
            'topbar_banner_medium',
            'topbar_banner_small',
            'topbar_banner_link',
            'helpline_number',
            'header_nav_menu_text',
            'header_menu_labels',
            'header_menu_links',

            'footer_title',
            'footer_description',
            'footer_logo',
            'about_us_description',
            'contact_address',
            'contact_phone',
            'contact_email',
            'widget_one',
            'widget_one_labels',
            'widget_one_links',
            'widget_two',
            'widget_two_labels',
            'widget_two_links',
            'widget_three',
            'widget_three_labels',
            'widget_three_links',
            'frontend_copyright_text',
            'show_social_links',
            'facebook_link',
            'twitter_link',
            'instagram_link',
            'youtube_link',
            'linkedin_link',
        ],

        'store_admin_blocked_route_names' => [
            'update',
            'update.*',
            'activation.index',
            'payment.activation',
            'payment_method.index',
            'payment_method.update',
            'env_key_update.update',
            'google_analytics.update',
            'google_recaptcha.update',
            'google-map.update',
            'google-firebase.update',
            'business_settings.update.activation',
            'business_settings.vendor_commission.update',
            'business_settings.vendor_commission',
            'seller_verification_form.update',
            'shipping_configuration.update',
            'roles.*',
            'staffs.*',
            'addons.*',
            'sellers.*',
            'seller.requests.*',
            'withdraw_requests.*',
            'notification.settings',
            'notification-type.*',
            'notification_type.*',
            'custom_notification*',
            'custom-notifications.*',
            'custom_notified_customers_list',
            'currency.*',
            'your_currency.update',
            'tax.*',
            'languages.*',
            'app-translations.*',
            'customer_packages.*',
            'seller_packages.*',
            'pickup_point.*',
            'countries.*',
            'states.*',
            'carriers.*',
            'zones.*',
            'cities.*',
            'delivery-boys.*',
            'delivery-boy.*',
            'delivery-boy-configuration',
            'delivery-boys-payment-histories',
            'delivery-boys-collection-histories',
            'paid-to-delivery-boy',
            'collection-from-delivery-boy',
            'orders.delivery-boy-assign',
            'earning_payout_report.index',
            'in_house_sale_report.index',
            'seller_sale_report.index',
            'stock_report.index',
            'wish_report.index',
            'user_search_report.index',
            'commission-log.index',
            'wallet-history.index',
            'cache.clear',
            'system_update',
            'import_demo_data',
            'uploaded-files.*',
            'bulk-uploaded-files-delete',
            'poin-of-sales.*',
            'pos.*',
            'admin.invoice.thermal_printer',
        ],

        'store_admin_blocked_route_uris' => [
            'admin/admin-permissions',
            'admin/all-file',
        ],
    ],
];
