@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><div class="row"><div class="col"><h5 class="mb-0 h6">{{ translate('Sales Returns') }}</h5></div>@can('sales_returns.create')<div class="col text-right"><a class="btn btn-primary" href="{{ route('operations.sales-returns.create') }}">{{ translate('Create Sales Return') }}</a></div>@endcan</div></div>
<div class="card"><div class="card-body">
    <form method="GET" class="row gutters-10 mb-3">
        <div class="col-md-2"><select class="form-control" name="status"><option value="">{{ translate('All statuses') }}</option>@foreach(['draft', 'requested', 'approved', 'rejected', 'completed', 'cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ translate(ucfirst($status)) }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-control" name="return_type"><option value="">{{ translate('All return types') }}</option>@foreach(['customer_return', 'admin_return', 'pos_return'] as $type)<option value="{{ $type }}" @selected(request('return_type') === $type)>{{ translate(ucfirst(str_replace('_', ' ', $type))) }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-control" name="order_id"><option value="">{{ translate('All orders') }}</option>@foreach($orders as $order)<option value="{{ $order->id }}" @selected((string) request('order_id') === (string) $order->id)>#{{ $order->id }} {{ $order->code }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-control" name="completed"><option value="">{{ translate('Completion status') }}</option><option value="yes" @selected(request('completed') === 'yes')>{{ translate('Completed') }}</option><option value="no" @selected(request('completed') === 'no')>{{ translate('Not completed') }}</option></select></div>
        <div class="col-md-2"><input type="date" class="form-control" name="from" value="{{ request('from') }}"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="{{ request('to') }}"></div>
        <div class="col-12 mt-2"><button class="btn btn-soft-primary">{{ translate('Filter') }}</button></div>
    </form>
    <div class="table-responsive"><table class="table aiz-table mb-0"><thead><tr><th>{{ translate('Number') }}</th><th>{{ translate('Order') }}</th><th>{{ translate('Customer') }}</th><th>{{ translate('Status') }}</th><th>{{ translate('Type') }}</th><th>{{ translate('Items / Qty') }}</th><th>{{ translate('Total / Cost') }}</th><th>{{ translate('Profit Reversal') }}</th><th>{{ translate('Completed at') }}</th><th></th></tr></thead><tbody>
    @forelse($salesReturns as $salesReturn)<tr><td>{{ $salesReturn->return_number }}</td><td>#{{ $salesReturn->order_id }} {{ $salesReturn->order?->code }}</td><td>{{ $salesReturn->order?->user?->name ?: '-' }}</td><td><span class="badge badge-info">{{ translate(ucfirst($salesReturn->status)) }}</span></td><td>{{ translate(ucfirst(str_replace('_', ' ', $salesReturn->return_type))) }}</td><td>{{ $salesReturn->items->count() }} / {{ $salesReturn->items->sum('quantity') }}</td><td>{{ $salesReturn->total_amount }} / {{ $salesReturn->total_cost }}</td><td>{{ $salesReturn->profit_reversal_amount }}</td><td>{{ optional($salesReturn->completed_at)->format('Y-m-d H:i') ?: '-' }}</td><td class="text-right"><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.sales-returns.show', $salesReturn) }}">{{ translate('View') }}</a></td></tr>@empty<tr><td colspan="10" class="text-center text-muted">{{ translate('No sales returns found.') }}</td></tr>@endforelse
    </tbody></table></div><div class="aiz-pagination">{{ $salesReturns->links() }}</div>
</div></div>
@endsection
