@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><div class="row"><div class="col"><h5 class="mb-0 h6">{{ $salesReturn->return_number }} <span class="badge badge-info">{{ translate(ucfirst($salesReturn->status)) }}</span></h5></div><div class="col text-right"><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.sales-returns') }}">{{ translate('Sales Returns') }}</a></div></div></div>
<div class="alert alert-info">{{ translate('This records stock and cost reversal only. A financial refund or credit note is not created.') }}</div>
<div class="card"><div class="card-body"><div class="row"><div class="col-md-4"><strong>{{ translate('Order') }}:</strong> #{{ $salesReturn->order_id }} {{ $salesReturn->order?->code }}</div><div class="col-md-4"><strong>{{ translate('Customer') }}:</strong> {{ $salesReturn->order?->user?->name ?: '-' }}</div><div class="col-md-4"><strong>{{ translate('Type') }}:</strong> {{ translate(ucfirst(str_replace('_', ' ', $salesReturn->return_type))) }}</div></div><div class="row mt-2"><div class="col-md-6"><strong>{{ translate('Reason') }}:</strong> {{ $salesReturn->reason ?: '-' }}</div><div class="col-md-6"><strong>{{ translate('Notes') }}:</strong> {{ $salesReturn->notes ?: '-' }}</div></div></div></div>
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Return items') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Product') }}</th><th>{{ translate('Variant / SKU / Barcode') }}</th><th>{{ translate('Returned') }}</th><th>{{ translate('Unit Price') }}</th><th>{{ translate('Tax') }}</th><th>{{ translate('Discount') }}</th><th>{{ translate('Cost Price') }}</th><th>{{ translate('Total Cost') }}</th><th>{{ translate('Profit Reversal') }}</th><th>{{ translate('Stock Reversed') }}</th></tr></thead><tbody>@foreach($salesReturn->items as $item)<tr><td>{{ $item->product?->name ?: '#'.$item->product_id }}</td><td>{{ $item->productStock?->variant ?: $item->variant ?: '-' }}<br><small>{{ $item->productStock?->sku ?: '-' }} / {{ $item->productStock?->barcode ?: $item->product?->barcode ?: '-' }}</small></td><td>{{ $item->quantity }}</td><td>{{ $item->unit_price }}</td><td>{{ $item->tax_amount }}</td><td>{{ $item->discount_amount }}</td><td>@if($item->cost_price === null)<span class="text-warning">{{ translate('Unavailable') }}</span>@else{{ $item->cost_price }}@endif</td><td>{{ $item->total_cost }}</td><td>{{ $item->profit_reversal_amount }}</td><td>{{ $item->stock_reversed_quantity }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card"><div class="card-body"><div class="row"><div class="col-md-3"><strong>{{ translate('Subtotal') }}:</strong> {{ $salesReturn->subtotal_amount }}</div><div class="col-md-2"><strong>{{ translate('Tax') }}:</strong> {{ $salesReturn->tax_amount }}</div><div class="col-md-2"><strong>{{ translate('Discount') }}:</strong> {{ $salesReturn->discount_amount }}</div><div class="col-md-2"><strong>{{ translate('Total Cost') }}:</strong> {{ $salesReturn->total_cost }}</div><div class="col-md-3"><strong>{{ translate('Profit Reversal') }}:</strong> {{ $salesReturn->profit_reversal_amount }}</div></div><div class="mt-2"><strong>{{ translate('Stock reversal status') }}:</strong> {{ $salesReturn->stock_reversed_at ? translate('Completed') : translate('Not reversed') }}</div></div></div>
@can('sales_returns.complete')
@if(!in_array($salesReturn->status, ['completed', 'rejected', 'cancelled']))
<form method="POST" action="{{ route('operations.sales-returns.complete', $salesReturn) }}" class="mb-3">@csrf <button class="btn btn-success">{{ translate('Complete return and reverse stock') }}</button></form>
@endif
@endcan
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Stock reversal trace') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Date') }}</th><th>{{ translate('Product') }}</th><th>{{ translate('Reference') }}</th><th>{{ translate('Quantity') }}</th><th>{{ translate('Unit Cost') }}</th><th>{{ translate('Total Cost') }}</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->created_at }}</td><td>{{ $movement->product?->name ?: '#'.$movement->product_id }}</td><td>{{ $movement->reference_type }} #{{ $movement->reference_id }}</td><td>{{ $movement->quantity }}</td><td>{{ $movement->unit_cost }}</td><td>{{ $movement->total_cost }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">{{ translate('No stock reversal movements yet.') }}</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header"><h6 class="mb-0">{{ translate('Accounting event status') }}</h6></div><div class="card-body table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>{{ translate('Status') }}</th><th>{{ translate('Amount') }}</th><th>{{ translate('Cost') }}</th><th>{{ translate('Profit') }}</th><th>{{ translate('Posted at') }}</th></tr></thead><tbody>@forelse($accountingEvents as $event)<tr><td>{{ $event->status }}</td><td>{{ $event->amount }}</td><td>{{ $event->cost_amount }}</td><td>{{ $event->profit_amount }}</td><td>{{ $event->posted_at }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ translate('No accounting event yet.') }}</td></tr>@endforelse</tbody></table></div></div>
@endsection
