@extends('backend.layouts.app')

@section('content')
<div class="aiz-titlebar text-left mt-2 mb-3"><h5 class="mb-0 h6">{{ translate('Cashier Shifts') }}</h5></div>
<div class="card"><div class="card-body">
    <form method="GET" class="row gutters-10 mb-3">
        <div class="col-md-2"><select class="form-control" name="status"><option value="">{{ translate('All statuses') }}</option>@foreach(['open','closed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ translate(ucfirst($status)) }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-control" name="cashbox_id"><option value="">{{ translate('All cashboxes') }}</option>@foreach($cashboxes as $cashbox)<option value="{{ $cashbox->id }}" @selected((string) request('cashbox_id') === (string) $cashbox->id)>{{ $cashbox->name }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-control" name="opened_by"><option value="">{{ translate('All users') }}</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('opened_by') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
        <div class="col-md-2"><input type="date" class="form-control" name="date_from" value="{{ request('date_from') }}"></div><div class="col-md-2"><input type="date" class="form-control" name="date_to" value="{{ request('date_to') }}"></div>
        <div class="col-md-2"><label class="aiz-checkbox"><input type="checkbox" name="open_only" value="1" @checked(request('open_only'))><span class="aiz-square-check"></span>{{ translate('Open only') }}</label><label class="aiz-checkbox ml-2"><input type="checkbox" name="has_difference" value="1" @checked(request('has_difference'))><span class="aiz-square-check"></span>{{ translate('Has difference') }}</label><button class="btn btn-soft-primary btn-sm mt-2">{{ translate('Filter') }}</button></div>
    </form>
    <div class="table-responsive"><table class="table aiz-table mb-0"><thead><tr><th>{{ translate('Cashbox') }}</th><th>{{ translate('Opened By') }}</th><th>{{ translate('Status') }}</th><th>{{ translate('Opened At') }}</th><th>{{ translate('Opening') }}</th><th>{{ translate('Expected') }}</th><th>{{ translate('Actual') }}</th><th>{{ translate('Difference') }}</th><th></th></tr></thead><tbody>
        @forelse($shifts as $shift)<tr><td>{{ $shift->cashbox?->name ?: '-' }}</td><td>{{ $shift->opener?->name ?: '-' }}</td><td><span class="badge badge-{{ $shift->isOpen() ? 'success' : 'secondary' }}">{{ translate(ucfirst($shift->status)) }}</span></td><td>{{ optional($shift->opened_at)->format('Y-m-d H:i') }}</td><td>{{ number_format((float) $shift->opening_balance, 2) }}</td><td>{{ number_format((float) $shift->expected_cash, 2) }}</td><td>{{ $shift->actual_cash === null ? '-' : number_format((float) $shift->actual_cash, 2) }}</td><td>{{ $shift->cash_difference === null ? '-' : number_format((float) $shift->cash_difference, 2) }}</td><td class="text-right"><a class="btn btn-soft-primary btn-sm" href="{{ route('operations.cash-shifts.show', $shift) }}">{{ translate('View') }}</a>@if($canCloseShift && $shift->isOpen()) <a class="btn btn-primary btn-sm" href="{{ route('operations.cash-shifts.close.form', $shift) }}">{{ translate('Close') }}</a>@endif</td></tr>@empty<tr><td colspan="9" class="text-center text-muted">{{ translate('No cashier shifts found.') }}</td></tr>@endforelse
    </tbody></table></div><div class="aiz-pagination">{{ $shifts->links() }}</div>
</div></div>
@endsection
