@extends('backend.layouts.app')

@section('content')
@php($settings = array_merge([
    'logo_enabled' => true, 'logo_position' => 'left', 'primary_color' => '#2563EB',
    'secondary_color' => '#64748B', 'font_size' => 10, 'show_store_name' => true,
    'show_supplier_info' => true, 'show_customer_info' => true, 'show_barcode' => true,
    'show_sku' => true, 'show_tax' => true, 'show_discount' => true, 'show_family' => false,
    'show_footer' => true, 'footer_text' => 'Generated by CoreMarket.', 'columns' => [],
], (array) old('settings', $template->settings ?? [])))
<div class="aiz-titlebar text-left mt-2 mb-3"><h1 class="h3">{{ $template->exists ? 'Edit Document Template' : 'Create Document Template' }}</h1></div>
<form method="POST" action="{{ $template->exists ? route('operations.document-templates.update', $template) : route('operations.document-templates.store') }}">
    @csrf @if($template->exists) @method('PUT') @endif
    <div class="card"><div class="card-body">
        @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
        <div class="row">
            <div class="col-md-6 form-group"><label>Name</label><input class="form-control" name="name" required value="{{ old('name', $template->name) }}"></div>
            <div class="col-md-6 form-group"><label>Code</label><input class="form-control" name="code" value="{{ old('code', $template->code) }}"></div>
            <div class="col-md-6 form-group"><label>Template Type</label><select class="form-control aiz-selectpicker" name="template_type">@foreach($types as $value => $label)<option value="{{ $value }}" @selected(old('template_type', $template->template_type) === $value)>{{ $label }}</option>@endforeach</select></div>
            <div class="col-md-6 form-group"><label>Paper Type</label><select class="form-control aiz-selectpicker" name="paper_type">@foreach($paperTypes as $value => $label)<option value="{{ $value }}" @selected(old('paper_type', $template->paper_type ?: 'a4') === $value)>{{ $label }}</option>@endforeach</select></div>
            @foreach(['width_mm' => 'Width (mm)', 'height_mm' => 'Height (mm)', 'margin_top_mm' => 'Top Margin', 'margin_right_mm' => 'Right Margin', 'margin_bottom_mm' => 'Bottom Margin', 'margin_left_mm' => 'Left Margin'] as $field => $label)
                <div class="col-md-4 form-group"><label>{{ $label }}</label><input type="number" step="0.1" class="form-control" name="{{ $field }}" value="{{ old($field, $template->{$field}) }}"></div>
            @endforeach
            <div class="col-md-4 form-group"><label>Primary Color</label><input type="color" class="form-control" name="primary_color" value="{{ old('primary_color', $settings['primary_color']) }}"></div>
            <div class="col-md-4 form-group"><label>Secondary Color</label><input type="color" class="form-control" name="secondary_color" value="{{ old('secondary_color', $settings['secondary_color']) }}"></div>
            <div class="col-md-4 form-group"><label>Font Size</label><input type="number" step="0.5" class="form-control" name="font_size" value="{{ old('font_size', $settings['font_size']) }}"></div>
            <div class="col-md-4 form-group"><label>Logo Position</label><select class="form-control" name="logo_position">@foreach(['left','center','right'] as $position)<option @selected(old('logo_position', $settings['logo_position']) === $position)>{{ $position }}</option>@endforeach</select></div>
            <div class="col-12 form-group"><label>Footer Text</label><textarea class="form-control" name="footer_text" rows="2">{{ old('footer_text', $settings['footer_text']) }}</textarea></div>
        </div>
        <h6>Visible Columns</h6>
        <div class="row mb-3">@foreach($allowedColumns as $column)<label class="col-md-3 mb-2"><input type="checkbox" name="columns[]" value="{{ $column }}" @checked(in_array($column, old('columns', $settings['columns']), true))> {{ \Illuminate\Support\Str::headline($column) }}</label>@endforeach</div>
        <h6>Display Options</h6>
        <div class="row">
            @foreach(['logo_enabled','show_store_name','show_supplier_info','show_customer_info','show_barcode','show_sku','show_tax','show_discount','show_family','show_footer'] as $option)
                <label class="col-md-3 mb-2"><input type="checkbox" name="{{ $option }}" value="1" @checked(old($option, $settings[$option]))> {{ \Illuminate\Support\Str::headline($option) }}</label>
            @endforeach
            <label class="col-md-3 mb-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $template->exists ? $template->is_active : true))> Active</label>
            <label class="col-md-3 mb-2"><input type="checkbox" name="is_default" value="1" @checked(old('is_default', $template->is_default))> Default</label>
        </div>
    </div><div class="card-footer text-right"><button class="btn btn-primary">Save Template</button></div></div>
</form>
@endsection
